# Generated by Django 4.1.2 on 2023-06-25 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spanish_inquisition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('join_code', models.CharField(blank=True, max_length=100, null=True)),
                ('first_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_quizzes', to=settings.AUTH_USER_MODEL)),
                ('owning_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
                ('second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_quizzes', to=settings.AUTH_USER_MODEL)),
                ('third_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('choiceA', models.CharField(max_length=200)),
                ('choiceB', models.CharField(max_length=200)),
                ('choiceC', models.CharField(max_length=200)),
                ('choiceD', models.CharField(max_length=200)),
                ('correct_choice', models.CharField(choices=[('a', 'Choice A'), ('b', 'Choice B'), ('c', 'Choice C'), ('d', 'Choice D')], max_length=1)),
                ('prompt_display_time', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='spanish_inquisition.quiz')),
            ],
        ),
    ]
